services:
  scheduleapi:
    image: scheduleapi
    build:
      context: .
      dockerfile: ScheduleAPI/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/Data/database.db;Mode=ReadOnly;Cache=Shared
    volumes: 
      - ./Data:/app/Data
  
  
  scheduleupdater:
    image: scheduleupdater
    build:
      context: .
      dockerfile: ScheduleUpdater/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=/app/Data/database.db;Mode=ReadWrite;Cache=Shared
    volumes:
      - ./Data:/app/Data

